[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/build"
  functions = "backend/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9" 