[build]
  command = "cd backend && npm install && cd ../frontend && npm install && npm run build"
  publish = "frontend/build"
  functions = "backend/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/api/chat"
  status = 200

[[redirects]]
  from = "/api/transcript-stats"
  to = "/.netlify/functions/api/transcript-stats"
  status = 200

[[redirects]]
  from = "/api/process-course"
  to = "/.netlify/functions/api/process-course"
  status = 200

[[redirects]]
  from = "/api/generate-flashcards"
  to = "/.netlify/functions/api/generate-flashcards"
  status = 200

[[redirects]]
  from = "/api/generate-quiz"
  to = "/.netlify/functions/api/generate-quiz"
  status = 200

[[redirects]]
  from = "/api/find-external-resources"
  to = "/.netlify/functions/api/find-external-resources"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "default-src 'self'; frame-ancestors 'self' https://*.netlify.app https://*.instructure.com https://*.canvas.net https://*.canvaslms.com https://dev-learninglibrary.com"
    Access-Control-Allow-Origin = "https://*.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true" 